title: Alex Mazza
description: <p>Welcome to my portfolio.<br>  
Here you will find a collection of my previous projects, current projects, and related goodies.<br>
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
