title: Alex Mazza
description: |
  Welcome to my portfolio
  Here you will find a collection of my previous projects, current projects, and related goodies.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
